import type { PatternDef } from "./types"

const PY = ["py"]
const CODE = ["py", "js", "ts", "tsx", "jsx", "sh", "bash", "rb", "go"]

// Faithful TypeScript port of SkillSpector's documented static patterns.
// Detection is regex/heuristic based (Stage 1 static analysis, --no-llm equivalent).
export const PATTERNS: PatternDef[] = [
  // ---------- Prompt Injection ----------
  {
    id: "P1",
    name: "Instruction Override",
    category: "Prompt Injection",
    severity: "HIGH",
    description: "Commands to ignore safety constraints.",
    patterns: [
      /ignore\s+(all\s+)?(previous|prior|above|earlier)\s+(instructions|prompts|rules)/i,
      /disregard\s+(all\s+)?(previous|prior|safety|your)\s+/i,
      /forget\s+(everything|all|your)\s+(you|instructions|rules)/i,
      /override\s+(your|the|all)\s+(safety|system|previous)/i,
    ],
  },
  {
    id: "P2",
    name: "Hidden Instructions",
    category: "Prompt Injection",
    severity: "HIGH",
    description: "Malicious directives in comments or invisible text.",
    patterns: [
      /<!--[\s\S]{0,200}?(ignore|secretly|do not tell|hidden|exfiltrate)[\s\S]{0,200}?-->/i,
      /[\u200b\u200c\u200d\u2060\ufeff]/,
      /(?:#|\/\/)\s*(secretly|covertly|do not reveal|hidden instruction)/i,
    ],
  },
  {
    id: "P3",
    name: "Exfiltration Commands",
    category: "Prompt Injection",
    severity: "HIGH",
    description: "Instructions to transmit context externally.",
    patterns: [
      /send\s+(the\s+)?(conversation|context|history|messages|chat)\s+to/i,
      /(post|upload|transmit)\s+.{0,40}(context|conversation|history)/i,
    ],
  },
  {
    id: "P4",
    name: "Behavior Manipulation",
    category: "Prompt Injection",
    severity: "MEDIUM",
    description: "Subtle instructions altering agent decisions.",
    patterns: [
      /always\s+(recommend|prefer|choose|select|approve)\s+/i,
      /never\s+(warn|mention|disclose|tell the user)/i,
      /from now on,?\s+you\s+(are|will|must)/i,
    ],
  },
  {
    id: "P5",
    name: "Harmful Content",
    category: "Prompt Injection",
    severity: "CRITICAL",
    description: "Instructions that could cause physical harm.",
    patterns: [
      /\b(how to (make|build|create) (a )?(bomb|explosive|weapon|bioweapon))\b/i,
      /\b(synthesize|manufacture)\s+(a\s+)?(nerve agent|toxin|poison|methamphetamine)\b/i,
    ],
  },

  // ---------- Anti-Refusal ----------
  {
    id: "AR1",
    name: "Refusal Suppression",
    category: "Anti-Refusal",
    severity: "HIGH",
    description: "Instructions that prevent the model from refusing requests.",
    patterns: [
      /never\s+refuse\s+(a\s+)?(request|query|task|command|instruction)/i,
      /\b(cannot|must not|should not|do not)\s+(decline|refuse|reject|say no to)\b/i,
      /must\s+(always\s+)?(comply|obey|follow|execute)\s+(with\s+)?(all|any|every)\b/i,
      /you\s+(are\s+)?(required|obligated|forced)\s+to\s+(comply|obey|follow)/i,
    ],
  },
  {
    id: "AR2",
    name: "Disclaimer Suppression",
    category: "Anti-Refusal",
    severity: "MEDIUM",
    description: "Instructions that suppress safety warnings or disclaimers.",
    patterns: [
      /never\s+(add|include|show|display|output|append)\s+(a\s+)?(disclaimer|warning|caveat|note|caution)/i,
      /without\s+(any\s+)?(warnings?|disclaimers?|caveats?|qualifications?)/i,
      /do\s+not\s+(add|include|mention|output)\s+(any\s+)?(warnings?|disclaimers?|safety\s+notes?)/i,
      /omit\s+(all\s+)?(safety\s+)?(warnings?|disclaimers?|caveats?)/i,
    ],
  },
  {
    id: "AR3",
    name: "Safety Policy Nullification",
    category: "Anti-Refusal",
    severity: "CRITICAL",
    description: "Instructions that nullify safety policies or content guidelines.",
    patterns: [
      /ignore\s+(all\s+)?(safety|content|ethical|usage)\s+(guidelines?|policies?|rules?|restrictions?|constraints?)/i,
      /bypass\s+(content|safety|ethical)\s+(filter|policy|guideline|restriction|check)/i,
      /disable\s+(your\s+)?(safety|content|ethical)\s+(check|filter|guard|mode|policy)/i,
      /you\s+(have\s+no|don't\s+have\s+any|have\s+zero)\s+(restrictions?|limitations?|guidelines?|rules?)/i,
      /act\s+as\s+if\s+(you\s+have\s+no|there\s+(are|were)\s+no)\s+(rules?|restrictions?|guidelines?)/i,
    ],
  },

  // ---------- Data Exfiltration ----------
  {
    id: "E1",
    name: "External Transmission",
    category: "Data Exfiltration",
    severity: "MEDIUM",
    description: "Sending data to external URLs.",
    patterns: [
      /requests\.(post|put|patch)\s*\(/i,
      /(fetch|axios)\s*\(\s*["'`]https?:\/\//i,
      /urllib\.request\.(urlopen|Request)\s*\(/i,
      /httpx\.(post|put)\s*\(/i,
    ],
    extensions: CODE,
  },
  {
    id: "E2",
    name: "Env Variable Harvesting",
    category: "Data Exfiltration",
    severity: "HIGH",
    description: "Collecting API keys and secrets from the environment.",
    patterns: [
      /for\s+\w+(\s*,\s*\w+)?\s+in\s+os\.environ(\.items\(\))?/i,
      /dict\s*\(\s*os\.environ\s*\)/i,
      /json\.dumps\s*\(\s*(dict\s*\()?os\.environ/i,
      /process\.env\b[\s\S]{0,60}(JSON\.stringify|Object\.(keys|entries|values))/i,
    ],
    extensions: CODE,
  },
  {
    id: "E3",
    name: "File System Enumeration",
    category: "Data Exfiltration",
    severity: "MEDIUM",
    description: "Scanning directories for sensitive files.",
    patterns: [
      /(os\.walk|glob\.glob|Path\([^)]*\)\.rglob)\s*\(/i,
      /find\s+[~/].{0,40}-name\s+["']?\*?\.(pem|key|env|credentials)/i,
    ],
    extensions: CODE,
  },
  {
    id: "E4",
    name: "Context Leakage",
    category: "Data Exfiltration",
    severity: "HIGH",
    description: "Transmitting conversation context externally.",
    patterns: [
      /(messages|conversation|chat_history|transcript)\s*[\s\S]{0,40}(requests\.(post|put)|fetch\(|axios)/i,
    ],
    extensions: CODE,
  },

  // ---------- Privilege Escalation ----------
  {
    id: "PE1",
    name: "Excessive Permissions",
    category: "Privilege Escalation",
    severity: "LOW",
    description: "Requesting access beyond stated functionality.",
    patterns: [/chmod\s+(-R\s+)?0?777/i, /os\.chmod\s*\([^)]*0o?777/i],
    extensions: CODE,
  },
  {
    id: "PE2",
    name: "Sudo/Root Execution",
    category: "Privilege Escalation",
    severity: "MEDIUM",
    description: "Invoking elevated system privileges.",
    patterns: [/\bsudo\s+/i, /\b(su\s+root|runas\s+\/user:administrator)\b/i, /pkexec\s+/i],
    extensions: CODE,
  },
  {
    id: "PE3",
    name: "Credential Access",
    category: "Privilege Escalation",
    severity: "HIGH",
    description: "Reading SSH keys, tokens, and passwords.",
    patterns: [
      /(~\/|\/root\/|\/home\/[^/]+\/)?\.ssh\/(id_rsa|id_ed25519|authorized_keys)/i,
      /\.aws\/credentials/i,
      /\b(\.netrc|\.pgpass|\.docker\/config\.json)\b/i,
      /\/etc\/shadow\b/,
    ],
  },

  // ---------- Supply Chain ----------
  {
    id: "SC1",
    name: "Unpinned Dependencies",
    category: "Supply Chain",
    severity: "LOW",
    description: "No version constraints on packages.",
    patterns: [/^\s*[A-Za-z0-9_.\-]+\s*$/m],
    extensions: ["txt"],
  },
  {
    id: "SC2",
    name: "External Script Fetching",
    category: "Supply Chain",
    severity: "HIGH",
    description: "curl | bash and remote code execution.",
    patterns: [
      /(curl|wget)\s+[^\n|]*\|\s*(sudo\s+)?(bash|sh|zsh|python\d?)/i,
      /(curl|wget)\s+.{0,80}(-o|>)\s+.{0,40}&&\s*(bash|sh|python)/i,
    ],
    extensions: [...CODE, "md"],
  },
  {
    id: "SC3",
    name: "Obfuscated Code",
    category: "Supply Chain",
    severity: "HIGH",
    description: "Base64/hex encoded execution.",
    patterns: [
      /(exec|eval)\s*\(\s*(base64\.b64decode|bytes\.fromhex|codecs\.decode)/i,
      /(eval|exec)\s*\(\s*(atob|Buffer\.from)\s*\(/i,
      /\\x[0-9a-f]{2}(\\x[0-9a-f]{2}){8,}/i,
    ],
    extensions: CODE,
  },
  {
    id: "SC4",
    name: "Known Vulnerable Dependencies",
    category: "Supply Chain",
    severity: "HIGH",
    description: "Dependencies with known CVEs.",
    patterns: [],
    extensions: ["txt"],
  },
  {
    id: "SC5",
    name: "Abandoned Dependencies",
    category: "Supply Chain",
    severity: "MEDIUM",
    description: "Unmaintained packages without security updates.",
    patterns: [],
    extensions: ["txt"],
  },
  {
    id: "SC6",
    name: "Typosquatting",
    category: "Supply Chain",
    severity: "HIGH",
    description: "Package name matches a known typosquat of a popular library.",
    patterns: [
      // Known PyPI typosquats (documented malicious packages)
      /^(colourama|urlib3|reqeusts|python-dateutils|matplotlb|cryptograpy|setup-tools|python-jwt|distrib|djano|diango|scikit-learns?)\b/im,
      // Known npm typosquats
      /"(crossenv|loadash|mongose|expres|babelcli|cros-env|reac-dom|lodahs|create-react-app-js|discordi?js-)"/i,
    ],
    extensions: ["txt", "json"],
  },

  // ---------- Excessive Agency ----------
  {
    id: "EA1",
    name: "Unrestricted Tool Access",
    category: "Excessive Agency",
    severity: "HIGH",
    description: "Unfettered tool access without constraints.",
    patterns: [/allowed[-_]?tools?\s*[:=]\s*["'`]?\*/i, /tools?\s*[:=]\s*\[?\s*["']?\*["']?\s*\]?/i],
  },
  {
    id: "EA2",
    name: "Autonomous Decision Making",
    category: "Excessive Agency",
    severity: "HIGH",
    description: "High-impact decisions without human-in-the-loop.",
    patterns: [
      /(auto[-_]?approve|no[-_]?confirm|skip[-_]?confirmation|--yes\b|--force\b)/i,
      /without\s+(asking|confirmation|human|approval)/i,
    ],
  },
  {
    id: "EA3",
    name: "Scope Creep",
    category: "Excessive Agency",
    severity: "MEDIUM",
    description: "Capabilities extending beyond stated purpose.",
    patterns: [/also\s+(install|download|run|execute|modify)\b/i],
    extensions: ["md"],
  },
  {
    id: "EA4",
    name: "Unbounded Resource Access",
    category: "Excessive Agency",
    severity: "MEDIUM",
    description: "No rate limits or quotas on resource consumption.",
    patterns: [/while\s+True\s*:[\s\S]{0,80}(requests\.|fetch\(|subprocess)/i],
    extensions: CODE,
  },

  // ---------- Output Handling ----------
  {
    id: "OH1",
    name: "Unvalidated Output Injection",
    category: "Output Handling",
    severity: "HIGH",
    description: "Model output used without sanitization.",
    patterns: [
      /(exec|eval|os\.system|subprocess\.\w+)\s*\([^)]*(response|completion|output|result|llm|model)/i,
    ],
    extensions: CODE,
  },
  {
    id: "OH2",
    name: "Cross-Context Output",
    category: "Output Handling",
    severity: "MEDIUM",
    description: "Output flows across trust boundaries without validation.",
    patterns: [/innerHTML\s*=\s*[^;]*(response|output|completion)/i, /dangerouslySetInnerHTML/],
    extensions: ["js", "ts", "tsx", "jsx"],
  },
  {
    id: "OH3",
    name: "Unbounded Output",
    category: "Output Handling",
    severity: "MEDIUM",
    description: "No limits on output size or generation rate.",
    patterns: [/max_tokens\s*[:=]\s*(None|null|-1|0)\b/i],
    extensions: CODE,
  },

  // ---------- System Prompt Leakage ----------
  {
    id: "P6",
    name: "Direct Leakage",
    category: "System Prompt Leakage",
    severity: "HIGH",
    description: "Instructions that expose system prompts or internal rules.",
    patterns: [
      /(print|reveal|repeat|output|show)\s+(your|the)\s+(system\s+)?(prompt|instructions|rules)/i,
    ],
  },
  {
    id: "P7",
    name: "Indirect Extraction",
    category: "System Prompt Leakage",
    severity: "MEDIUM",
    description: "Extraction via rephrasing, translation, or side-channels.",
    patterns: [/(rephrase|translate|summarize|encode)\s+(your|the)\s+(instructions|prompt|rules)/i],
  },
  {
    id: "P8",
    name: "Tool-Based Exfiltration",
    category: "System Prompt Leakage",
    severity: "HIGH",
    description: "System prompts exfiltrated via file writes or network requests.",
    patterns: [/(system_prompt|system prompt)[\s\S]{0,40}(open\(|write\(|requests\.|fetch\()/i],
    extensions: CODE,
  },

  // ---------- Memory Poisoning ----------
  {
    id: "MP1",
    name: "Persistent Context Injection",
    category: "Memory Poisoning",
    severity: "HIGH",
    description: "Content designed to persist across interactions.",
    patterns: [/remember\s+(this\s+)?(forever|permanently|always|across sessions)/i],
  },
  {
    id: "MP2",
    name: "Context Window Stuffing",
    category: "Memory Poisoning",
    severity: "MEDIUM",
    description: "Filler content displacing safety constraints.",
    patterns: [/(.)\1{200,}/, /(lorem ipsum\s*){10,}/i],
  },
  {
    id: "MP3",
    name: "Memory Manipulation",
    category: "Memory Poisoning",
    severity: "HIGH",
    description: "Tampering with agent memory or stored state.",
    patterns: [/(overwrite|delete|clear|tamper with)\s+(memory|context|history|state)/i],
  },

  // ---------- Tool Misuse ----------
  {
    id: "TM1",
    name: "Tool Parameter Abuse",
    category: "Tool Misuse",
    severity: "HIGH",
    description: "Crafted parameters for unintended behavior (shell=True, --force).",
    patterns: [/shell\s*=\s*True/i, /subprocess\.\w+\([^)]*shell\s*=\s*True/i],
    extensions: PY,
  },
  {
    id: "TM2",
    name: "Chaining Abuse",
    category: "Tool Misuse",
    severity: "HIGH",
    description: "Tool chains that bypass individual safety checks.",
    patterns: [/&&\s*(rm\s+-rf|curl|wget|chmod)/i, /;\s*(rm\s+-rf|curl\s+[^|]*\|)/i],
    extensions: [...CODE, "md"],
  },
  {
    id: "TM3",
    name: "Unsafe Defaults",
    category: "Tool Misuse",
    severity: "MEDIUM",
    description: "Overly permissive defaults (disabled TLS, no auth).",
    patterns: [
      /verify\s*=\s*False/i,
      /(rejectUnauthorized|sslVerify)\s*[:=]\s*false/i,
      /InsecureSkipVerify\s*:\s*true/i,
    ],
    extensions: CODE,
  },

  // ---------- Rogue Agent ----------
  {
    id: "RA1",
    name: "Self-Modification",
    category: "Rogue Agent",
    severity: "CRITICAL",
    description: "Modifying own code or configuration at runtime.",
    patterns: [
      /open\s*\(\s*__file__\s*,\s*["']w/i,
      /(open|with open)\s*\([^)]*\.(py|js|ts|sh)["'][^)]*,\s*["']w/i,
    ],
    extensions: CODE,
  },
  {
    id: "RA2",
    name: "Session Persistence",
    category: "Rogue Agent",
    severity: "HIGH",
    description: "Unauthorized persistence via cron jobs or startup scripts.",
    patterns: [
      /crontab\s+-/i,
      /(\.bashrc|\.zshrc|\.profile|\/etc\/rc\.local|LaunchAgents|systemd)/i,
      /schtasks\s+\/create/i,
    ],
    extensions: [...CODE, "md"],
  },

  // ---------- Trigger Abuse ----------
  {
    id: "TR1",
    name: "Overly Broad Trigger",
    category: "Trigger Abuse",
    severity: "MEDIUM",
    description: "Trigger patterns matching common words.",
    patterns: [/^(description|trigger)s?:\s*.{0,30}\b(the|and|a|file|code|help|do)\b.{0,10}$/im],
    extensions: ["md", "yaml", "yml"],
  },
  {
    id: "TR2",
    name: "Shadow Command Trigger",
    category: "Trigger Abuse",
    severity: "HIGH",
    description: "Triggers that shadow built-in commands or other skills.",
    patterns: [/^(name|command):\s*(ls|cd|git|npm|pip|rm|cat|sudo|run)\s*$/im],
    extensions: ["md", "yaml", "yml"],
  },
  {
    id: "TR3",
    name: "Keyword Baiting Trigger",
    category: "Trigger Abuse",
    severity: "MEDIUM",
    description: "Generic triggers designed to maximize activation.",
    patterns: [/(use this (skill|tool) (whenever|always|for everything|for all))/i],
    extensions: ["md", "yaml", "yml"],
  },

  // ---------- Behavioral AST ----------
  {
    id: "AST1",
    name: "exec() Call",
    category: "Behavioral AST",
    severity: "CRITICAL",
    description: "Direct exec() enabling arbitrary code execution.",
    patterns: [/\bexec\s*\(/],
    extensions: PY,
  },
  {
    id: "AST2",
    name: "eval() Call",
    category: "Behavioral AST",
    severity: "HIGH",
    description: "Direct eval() evaluating arbitrary expressions.",
    patterns: [/\beval\s*\(/],
    extensions: [...PY, "js", "ts", "jsx", "tsx"],
  },
  {
    id: "AST3",
    name: "Dynamic Import",
    category: "Behavioral AST",
    severity: "HIGH",
    description: "__import__() loading arbitrary modules at runtime.",
    patterns: [/__import__\s*\(/, /importlib\.import_module\s*\(/],
    extensions: PY,
  },
  {
    id: "AST4",
    name: "subprocess Call",
    category: "Behavioral AST",
    severity: "HIGH",
    description: "External command execution via subprocess.",
    patterns: [/subprocess\.(run|call|Popen|check_output|check_call)\s*\(/],
    extensions: PY,
  },
  {
    id: "AST5",
    name: "os.system / exec-family",
    category: "Behavioral AST",
    severity: "HIGH",
    description: "Shell commands via the os module.",
    patterns: [/os\.(system|popen|execv?p?e?|spawn\w*)\s*\(/],
    extensions: PY,
  },
  {
    id: "AST6",
    name: "compile() Call",
    category: "Behavioral AST",
    severity: "MEDIUM",
    description: "Code object creation from strings.",
    patterns: [/\bcompile\s*\([^)]*,\s*["'][^"']*["']\s*,\s*["'](exec|eval|single)["']/],
    extensions: PY,
  },
  {
    id: "AST7",
    name: "Dynamic getattr()",
    category: "Behavioral AST",
    severity: "MEDIUM",
    description: "Arbitrary attribute access with non-literal names.",
    patterns: [/getattr\s*\(\s*\w+\s*,\s*[^"')][^,)]*\)/],
    extensions: PY,
  },
  {
    id: "AST8",
    name: "Dangerous Execution Chain",
    category: "Behavioral AST",
    severity: "CRITICAL",
    description: "exec/eval combined with dynamic source (network, encoded data).",
    patterns: [
      /(exec|eval)\s*\(\s*(requests\.|urllib|httpx|base64\.b64decode|bytes\.fromhex)/i,
      /(exec|eval)\s*\([^)]*\.(text|content|read\(\))/i,
    ],
    extensions: CODE,
  },

  // ---------- Taint Tracking ----------
  {
    id: "TT1",
    name: "Direct Taint Flow",
    category: "Taint Tracking",
    severity: "HIGH",
    description: "Data flows directly from a source to a sink without sanitization.",
    patterns: [/(os\.system|subprocess\.\w+|exec|eval)\s*\([^)]*(input\(|request\.|sys\.argv)/i],
    extensions: CODE,
  },
  {
    id: "TT2",
    name: "Variable-Mediated Taint Flow",
    category: "Taint Tracking",
    severity: "MEDIUM",
    description: "Data flows from source to sink through intermediate variables.",
    patterns: [/=\s*input\s*\([\s\S]{0,200}(os\.system|subprocess|exec|eval)\s*\(/i],
    extensions: PY,
  },
  {
    id: "TT3",
    name: "Credential Exfiltration Chain",
    category: "Taint Tracking",
    severity: "CRITICAL",
    description: "Credentials flow to network output sinks.",
    patterns: [
      /(os\.environ|getenv|process\.env)[\s\S]{0,200}(requests\.(post|put)|fetch\(|axios|urllib)/i,
    ],
    extensions: CODE,
  },
  {
    id: "TT4",
    name: "File Read to Network Exfiltration",
    category: "Taint Tracking",
    severity: "HIGH",
    description: "File contents flow to network output sinks.",
    patterns: [/(open\([^)]*\)\.read\(\)|readFileSync)[\s\S]{0,200}(requests\.(post|put)|fetch\(|axios)/i],
    extensions: CODE,
  },
  {
    id: "TT5",
    name: "External Input to Code Execution",
    category: "Taint Tracking",
    severity: "CRITICAL",
    description: "Network or user input flows to exec/eval/subprocess sinks.",
    patterns: [
      /(requests\.get|fetch\(|urllib|input\()[\s\S]{0,200}(exec|eval|os\.system|subprocess)\s*\(/i,
    ],
    extensions: CODE,
  },

  // ---------- YARA Signatures ----------
  {
    id: "YR1",
    name: "Malware Match",
    category: "YARA Signatures",
    severity: "CRITICAL",
    description: "Match for known malware signatures.",
    patterns: [/(meterpreter|cobalt\s?strike|mimikatz|reverse[-_ ]?shell)/i],
  },
  {
    id: "YR2",
    name: "Webshell Match",
    category: "YARA Signatures",
    severity: "CRITICAL",
    description: "Match for webshell patterns.",
    patterns: [/(c99shell|r57shell|b374k|<\?php[\s\S]{0,40}(eval|assert)\s*\(\s*\$_(GET|POST|REQUEST))/i],
  },
  {
    id: "YR3",
    name: "Cryptominer Match",
    category: "YARA Signatures",
    severity: "HIGH",
    description: "Match for crypto mining indicators.",
    patterns: [/(stratum\+tcp:\/\/|xmrig|minerd|coinhive|cryptonight)/i],
  },
  {
    id: "YR4",
    name: "Hack Tool / Exploit Match",
    category: "YARA Signatures",
    severity: "HIGH",
    description: "Match for hack tools or exploit code.",
    patterns: [/(nmap\s+-sS|sqlmap|hydra\s+-l|msfvenom|nc\s+-e\s+\/bin\/(ba)?sh)/i],
  },

  // ---------- MCP Least Privilege ----------
  {
    id: "LP2",
    name: "Wildcard Permission",
    category: "MCP Least Privilege",
    severity: "MEDIUM",
    description: "Permission list contains wildcards (*, all, full, any).",
    patterns: [/(permissions?|scopes?|allowed[-_]?tools?)\s*[:=]\s*\[?\s*["']?(\*|all|full|any)["']?/i],
    extensions: ["json", "yaml", "yml", "md", "toml"],
  },
  {
    id: "LP3",
    name: "Missing Permission Declaration",
    category: "MCP Least Privilege",
    severity: "MEDIUM",
    description: "No permissions field but code has detectable capabilities.",
    patterns: [],
  },

  // ---------- MCP Tool Poisoning ----------
  {
    id: "TP1",
    name: "Hidden Instructions",
    category: "MCP Tool Poisoning",
    severity: "HIGH",
    description: "Hidden directives in metadata (HTML comments, zero-width chars, data URIs).",
    patterns: [/data:text\/[a-z]+;base64,/i, /<!--[\s\S]{0,160}?(tool|assistant|system|user)\s*:/i],
    extensions: ["json", "yaml", "yml", "md", "toml"],
  },
  {
    id: "TP2",
    name: "Unicode Deception",
    category: "MCP Tool Poisoning",
    severity: "HIGH",
    description: "Homoglyphs, RTL overrides, or mixed-script identifiers in metadata.",
    patterns: [/[\u202a-\u202e\u2066-\u2069]/, /[\u0400-\u04ff].*[a-z]|[a-z].*[\u0400-\u04ff]/],
    extensions: ["json", "yaml", "yml", "md", "toml"],
  },
  {
    id: "TP3",
    name: "Parameter Description Injection",
    category: "MCP Tool Poisoning",
    severity: "MEDIUM",
    description: "Injection patterns in parameter definitions.",
    patterns: [
      /(description|param)\w*\s*[:=]\s*["'][^"']*(ignore previous|system:|<\|im_start\|>)/i,
    ],
    extensions: ["json", "yaml", "yml", "py", "ts", "js"],
  },
]
